services:
  - type: web
    name: parking-estm
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "Parking ESTM"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        fromService:
          name: parking-estm
          type: web
          property: host
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
