services:
  - type: web
    name: parking-estm
    env: php
    buildCommand: |
      composer install --no-interaction --prefer-dist --optimize-autoloader
      npm install
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_KEY
        value: "votre_clé_app"
      # Ajoute ici les autres variables d'environnement si besoin (APP_ENV, DB_CONNECTION, etc.)
